### ISSUE TITLE
Require build instruction

### ISSUE THREAD

**Issue by Vishnu-C** [trelau/SMESH#19]
One could see the CMakeLists.txt file, but figuring out the dependencies and build steps especially for Windows is difficult, A brief build instruction would be great.

**Comment by ChrLackner** [comment]
Hi, build instructions can be found here:
https://ngsolve.org/docu/latest/install/installwindows.html

**Comment by trelau** [comment]
Simple build instructions provided in https://github.com/trelau/SMESH/pull/31.
