### ISSUE TITLE
Cut 9.6.0 release

### ISSUE THREAD

**Issue by trelau** [trelau/SMESH#36]
Reminder to cut a new release for 9.6.0 when ready.

@looooo I see smesh-feedstock is now on 9.6.0. Seems safe to cut a release for this repo, right?

**Comment by looooo** [comment]
I already created a 9.6.0 package for conda-forge as I wanted to start with occt7.5 migration in the next days.

**Comment by trelau** [comment]
done here https://github.com/trelau/SMESH/releases/tag/v9.6.0.0
