### ISSUE TITLE
error: ISO C++17 does not allow dynamic exception specifications

### ISSUE THREAD

**Issue by looooo** [trelau/SMESH#40]
would be nice to add the patch for the exception again.
```
$PREFIX/include/smesh/SMESH/SMESH_Gen.hxx:70:5: error: ISO C++17 does not allow dynamic exception specifications
   70 |     throw(SALOME_Exception);
      |     ^~~~~
In file included from ../src/Mod/MeshPart/App/Mesher.cpp:49:
$PREFIX/include/smesh/StdMeshers/StdMeshers_MaxLength.hxx:38:33: error: ISO C++17 does not allow dynamic exception specifications
   38 |   void SetLength(double length) throw(SALOME_Exception);
      |                                 ^~~~~
In file included from ../src/Mod/MeshPart/App/Mesher.cpp:50:
$PREFIX/include/smesh/SMESH/SMESH_Mesh.hxx:136:5: error: ISO C++17 does not allow dynamic exception specifications
  136 |     throw(SALOME_Exception);
      |     ^~~~~

```

# Issue description

(Provide a short description, state the expected behavior and what actually happens.)

# Reproducible example code

(The code should be minimal, have no external dependencies, isolate the function(s) that cause breakage. Submit matched and complete snippets that can be easily compiled and run to diagnose the issue.)

**Comment by looooo** [comment]
https://github.com/trelau/SMESH/commit/eac52539e355ee0aaa5b3c6100274c23ff4492c4

**Comment by looooo** [comment]
I made a PR: #41

**Comment by trelau** [comment]
Fixed by #41 , right? Can we close?

**Comment by looooo** [comment]
Sure. Thx.

**Comment by adrianinsaval** [comment]
hi @trelau @looooo does this mean smesh can compile fine with c++17? freecad is now not building on conda due to forced usage of c++14 when using external smesh https://forum.freecad.org/viewtopic.php?p=669348#p669348
