### ISSUE TITLE
SMESH Dependencies

### ISSUE THREAD

**Issue by weiweiisok** [trelau/SMESH#56]
Hi, trelau, I have some urgent problems with smesh:
1. Whether your SMESH must have a dependenciy with pyocct?
2. And I have a project via tpaviot's pythonocc, but this package has not a SMESH module yet, so is it possible I use Pythonocc with your SMESH here?
3. I have install smesh via 'conda install -c conda-forge smesh', but I still can't import smesh module, and I also find that the file library of smesh only have two files named 'info' and 'Library', It's not a python file?
Forgive my ignorance please, I would be very grateful if you can provide any help.

**Comment by trelau** [comment]
@weiweiisok this project is the c++ library. Maybe try pySMESH (via conda). pyOCCT and pySMESH won't work with pythonocc since pyOCCT/pySMESH uses pybind11 to generate python bindings and pythonocc uses SWIG.
