### ISSUE TITLE
Missing option to build smesh without VTK

### ISSUE THREAD

**Issue by pkwok14** [trelau/SMESH#60]
I wonder if there is some possibility to build smesh as a library without VTK if one does not need visualization (assuming VTK isn't somehow needed for the core meshing functionality). As it is not it seems VTK is a hard coded requirement, but I wonder if there is some way to build it without going through all sources to eliminate VTK dependencies manually?

**Comment by trelau** [comment]
VTK is required as it provides much of the core mesh data structures that SMESH is built on or around.

Why do you want to avoid building VTK?

**Comment by pkwok14** [comment]
Ah, I see. I was thinking of building a small stand alone binary, and thought VTK was just used for visualization. And is kind of heavy dependency (in the context) and could be removed, but I guess not without a big redesign. Thanks for clarifying anyway.
