### ISSUE TITLE
Diffference from https://github.com/tpaviot/smesh ?

### ISSUE THREAD

**Issue by jiapei100** [trelau/SMESH#71]
May I ask a naive question:

What is the difference from this [https://github.com/trelau/SMESH](https://github.com/trelau/SMESH) and [https://github.com/tpaviot/smesh](https://github.com/tpaviot/smesh) ?

Cheers

**Comment by trelau** [comment]
They both reference the same codebase, but main difference is that this (trelau) SMESH is more up-to-date with the upstream Salome project. There is likely nothing stopping tpaviot from updating as well, it just perhaps hasn't been a priority. This repository has some scripts to pull upstream sources to make it easier to stay current whereas I think tpaviot repo relies on manual updates of the source code.
